config/routes.rb
Rails.application.routes.draw do
  get 'service/index'
  get 'service/new'
  get 'service/edit'
  get 'service/save'
  get 'service/delete'
  get '/service', to: 'service#index'

  get 'listing/show'
  get 'listing/new'
  get 'listing/saved'
  get 'listing/list'
  post 'listing/list'
  post 'listing/save'
  get 'listing/delete'
  get 'listing/edit'
  get '/buy', to: 'listing#list'
  get '/sell', to: 'listing#new'

  get 'page/home'
  get 'page/show'
  get 'page/not_found'

  get 'account/dashboard'
  get 'account/index'
  get 'account/edit'
  get 'account/login'
  get 'account/logout'
  get 'account/register'
  post 'account/save'
  post 'account/login_post'
  post 'account/register_post'

  namespace :admin do
    resources :listings, :users, :services, :admin_user, :settings, :attributes
  end

  match ':controller(/:action(/:id))', controller: /admin\/[^\/]+/, action: /[^\/]+_post/, via: [:post]
  match ':controller(/:action(/:id))', controller: /admin\/[^\/]+/, via: [:get]
  get '/admin', to: 'admin/index#dashboard'

  root 'page#home'

  get '/:page', to: 'page#show', page: /.*/

end

app/views/partial/_footer.html.erb
<nav id="footer-nav" class="row">
  <div class="small-6 small-offset-3 columns">
    <ul class="menu">
      <li>
        <%= link_to t(:buy),
          { controller: 'listing', action: 'list' } %>
        <span>&bull;</span>
      </li>
      <li>
        <%= link_to t(:sell_and_trade),
          { controller: 'listing', action: 'new' } %>
        <span>&bull;</span>
      </li>
      <li>
        <%= link_to t(:service_and_repair),
          { controller: 'service', action: 'new' } %>
        <span>&bull;</span>
      </li>
      <li>
        <%= link_to t(:my_account),
          { controller: 'account', action: 'login' } %>
      </li>
    </ul>
  </div>
</nav>
<%= content_tag :div, get_copyright_message,
  id: 'copyright', class: 'text-center' %>

app/views/partial/_head.html.erb
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : t(:title) %></title>


  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
</head>

app/views/partial/_header.html.erb
<div class="row" id="header-container">
  <div class="small-2 columns" id="logo">
    <%= link_to(image_tag("logo.jpg"), root_url) %>
  </div>
  <div class="small-7 columns text-left">
    <h3><%= t :online_automall %></h3>
    <span><%= t :slogan %></span>
  </div>
  <div class="small-3 columns">
    <%= render 'partial/toplinks' %>
  </div>
</div>

app/views/partial/_left.html.erb
<nav id="left-nav">
  <ul class="menu vertical">
    <li>
      <%= link_to t(:dashboard), { controller: 'account', action: 'dashboard' },
        class: 'button' %>
    </li>
    <li>
      <%= link_to t(:profile), { controller: 'account', action: 'edit' },
        class: 'button' %>
    </li>
    <li>
      <%= link_to t(:my_listings), { controller: 'listing', action: 'list' },
        class: 'button' %>
    </li>
    <li>
      <%= link_to t(:saved_listings), { controller: 'listing', action: 'saved' },
        class: 'button' %>
    </li>
  </ul>
</nav>

app/views/partial/_messages.html.erb
<% if get_flash_messages %>
<div id="flash-messages" class="small-12 columns">
  <% get_flash_messages.each do |name, msg| -%>
  <%= content_tag :p, msg, class: name + ' callout' %>
  <% end -%>
</div>
<% end %>

app/views/partial/_navigation.html.erb
<div class="row main-navigation">
  <ul class="menu medium-12 colums">
    <li>
      <%= link_to t(:buy), buy_url, class: 'button' %>
    </li>
    <li>
      <%= link_to t(:sell_and_trade), sell_url, class: 'button' %>
    </li>
    <li>
      <%= link_to t(:service_and_repair), service_url, class: 'button' %>
    </li>
  </ul>
</div>

app/views/partial/_right.html.erb
<nav id="right-nav">
  <ul class="menu">
    <li>Dashboard</li>
    <li>Profile</li>
    <li>My Listings</li>
    <li>Saved Listings</li>
  </ul>
</nav>

app/views/partial/_toplinks.html.erb
<nav id="top-links">
  <ul class="menu">
    <% if !is_user_logged_in? %>
    <li>
      <%= link_to t(:login), { controller: 'account',
        action: 'login' }, class: 'button' %>
    </li>
    <% else %>
    <li>
      <%= link_to t(:logout), { controller: 'account',
        action: 'logout' }, class: 'button' %>
    </li>
    <% end %>
    <li>
      <%= link_to t(:my_account), { controller: 'account',
        action: 'dashboard' }, class: 'button' %>
    </li>
  </ul>
</nav>